### ISSUE TITLE
gyp_chromium occasional failure

### ISSUE THREAD

**Issue by kuscsik** [01org/ozone-wayland#429]
Tested: latest chromium master branch

gyp_chromium occasionally fails with error: 

Updating projects from gyp files...
Traceback (most recent call last):
  File "build/gyp_chromium", line 12, in <module>
    execfile(__file__ + '.py')
  File "build/gyp_chromium.py", line 335, in <module>
    sys.exit(main())
  File "build/gyp_chromium.py", line 322, in main
    gyp_rc = gyp.main(args)
  File "/home/kuscsik/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 538, in main
    return gyp_main(args)
  File "/home/kuscsik/chromium/src/tools/gyp/pylib/gyp/__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "/home/kuscsik/chromium/src/tools/gyp/pylib/gyp/generator/ninja.py", line 2395, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "/home/kuscsik/chromium/src/toolchain/sysroots/x86_64-los-linux/usr/lib/python2.7/multiprocessing/pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/kuscsik/chromium/src/toolchain/sysroots/x86_64-los-linux/usr/lib/python2.7/multiprocessing/pool.py", line 558, in get
    raise self._value
KeyError: 'Debug'

**Comment by kuscsik** [comment]
Fixed in pull request:

**Comment by kuscsik** [comment]
https://github.com/01org/ozone-wayland/pull/428
