### ISSUE TITLE
chromium 48.0.2548 configure error

### ISSUE THREAD

**Issue by bgao** [01org/ozone-wayland#459]
I was using the latest 48.0.2548 recipe and encountered such error:

`
ERROR: Function failed: do_configure
ERROR: Logfile of failure stored in: 
Log data follows:
| DEBUG: Executing python function sysroot_cleansstate
| DEBUG: Python function sysroot_cleansstate finished
| DEBUG: Executing shell function do_configure
| Updating projects from gyp files...
| Exception: Failed to open test/data/webui/i18n_process_css_test.html while trying to flatten test/data/webui/i18n_process_css_test.html. (No such file or directory)
| Traceback (most recent call last):
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 491, in CallLoadTargetBuildFile
|     includes, depth, check, False)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 412, in LoadTargetBuildFile
|     build_file_data, PHASE_EARLY, variables, build_file_path)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
|     build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1302, in ProcessVariablesAndConditionsInList
|     ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
|     build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1302, in ProcessVariablesAndConditionsInList
|     ProcessVariablesAndConditionsInDict(item, phase, variables, build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1287, in ProcessVariablesAndConditionsInDict
|     build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 1306, in ProcessVariablesAndConditionsInList
|     expanded = ExpandVariables(item, phase, variables, build_file)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/gyp/pylib/gyp/input.py", line 886, in ExpandVariables
|     replacement = str(py_module.DoMain(parsed_contents[1:])).rstrip()
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/grit/grit_info.py", line 150, in DoMain
|     options.target_platform)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/grit/grit_info.py", line 97, in Inputs
|     files.update(node.GetHtmlResourceFilenames())
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/grit/grit/node/include.py", line 118, in GetHtmlResourceFilenames
|     allow_external_script=allow_external_script)
|   File "~/build/arago-tmp-external-linaro-toolchain/work/cortexa15t2hf-vfp-neon-3.14-linux-gnueabi/chromium/48.0.2548.0-r0/chromium-48.0.2548.0/tools/grit/grit/format/html_inline.py", line 412, in GetResourceFilenames
|     (e.filename, filename, e.strerror))
| Exception: Failed to open test/data/webui/i18n_process_css_test.html while trying to flatten test/data/webui/i18n_process_css_test.html. (No such file or directory)
| 
| Error processing node <?xml version="1.0" encoding="UTF-8"?>
| <include allowexternalscript="true" file="webui/i18n_process_css_test.html" flattenhtml="true" name="IDR_WEBUI_TEST_I18N_PROCESS_CSS_TEST" type="BINDATA" />
| WARNING: exit code 1 from a shell command.
| ERROR: Function failed: do_configure
ERROR: Task 7 (~/sources/meta-browser/recipes-browser/chromium/chromium_48.0.2548.0.bb, do_configure) failed with exit code '1'
`

It seems that files are missing from the Chromium source package.

**Comment by bgao** [comment]
Oops. The issue doesn't belong to this repo. Sorry...
